import type { Metadata } from "next";
import { Oswald , Inter } from "next/font/google";
import "./globals.css";
import Navber from "@/components/shared/Navber";
import Footer from "@/components/shared/Footer";


const OswaldFont = Oswald({
  variable:"--font-Oswald",
  subsets:["latin"]
})
const InterFont = Inter({
  variable:"--font-Inter",
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${OswaldFont.variable} ${InterFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navber/>
        <main className="flex-1">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
